// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/K-Kizuku/plesio-server/app/adapter/controller"
	"github.com/K-Kizuku/plesio-server/app/adapter/gateway"
	"github.com/K-Kizuku/plesio-server/app/driver/redis"
	"github.com/K-Kizuku/plesio-server/app/driver/ristretto"
	"github.com/K-Kizuku/plesio-server/app/usecase"
	"net"
)

// Injectors from wire.go:

func InitUDP(ln *net.UDPConn) controller.IController {
	iInMemoryCacheRepository := ristretto.NewCacheClient()
	iDataStoreRepository := redis.NewDataStoreClient()
	iClientRepository := gateway.NewClientRepository(iInMemoryCacheRepository, iDataStoreRepository)
	iRoomRepository := gateway.NewRoomRepository(iInMemoryCacheRepository, iDataStoreRepository)
	iMeetingUsecase := usecase.NewMeetingUsecase(iClientRepository, iRoomRepository)
	iMeetingController := controller.NewMeetingContrallor(iMeetingUsecase)
	iController := controller.NewUDPController(ln, iMeetingController)
	return iController
}

func InitTCP(ln *net.TCPConn) controller.IController {
	iInMemoryCacheRepository := ristretto.NewCacheClient()
	iDataStoreRepository := redis.NewDataStoreClient()
	iClientRepository := gateway.NewClientRepository(iInMemoryCacheRepository, iDataStoreRepository)
	iRoomRepository := gateway.NewRoomRepository(iInMemoryCacheRepository, iDataStoreRepository)
	iMeetingUsecase := usecase.NewMeetingUsecase(iClientRepository, iRoomRepository)
	iMeetingController := controller.NewMeetingContrallor(iMeetingUsecase)
	iController := controller.NewTCPController(ln, iMeetingController)
	return iController
}
